services:
  db:
    image: postgres:14
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    image: ghcr.io/stjude/mygpt-backend:latest
    command:
      - "/bin/sh"
      - "-c"
      - "python3 manage.py migrate --fake sessions zero && python3 manage.py migrate --fake-initial && python3 manage.py collectstatic --no-input && python3 manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./media:/media
    ports:
      - "${BACKEND_PORT:-8000}:8000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - ./.env_backend
    environment:
      OLLAMA_SERVER: ${OLLAMA_SERVER:-http://host.docker.internal:11434}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 30s
      timeout: 30s
      retries: 5
      start_period: 30s
    depends_on:
      db:
        condition: service_healthy

  grobid:
    image: lfoppiano/grobid:latest-crf
    ports:
      - "8070:8070"
    environment:
      JAVA_OPTS: -Xmx4g
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8070/"]
      interval: 30s
      timeout: 30s
      retries: 5
      start_period: 30s
